# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [2]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [3]:
# Load data here
df = pd.read_csv('data/listings.csv', sep=',')
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [39]:
# 1. How many listings are there with a price less than 100? 

less_than_hundred = df[ 'price' ] < 100
len(df[ less_than_hundred ])

22778

In [37]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.

in_brooklyn = df[ 'neighbourhood_group' ] == 'Brooklyn'
df_bk = df[ in_brooklyn ]
len(df_bk)

18632

In [36]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.

len(df[ less_than_hundred & in_brooklyn ])

10473

In [40]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.

names = [ 'Michael', 'David', 'John', 'Daniel' ]
condition = df.host_name.isin(names)
df[ condition ].head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,adjusted_price
52,16595,LOFT HAVEN ~ Six Windows ~ Bricks ~ Plants ~ Q...,64522,Daniel,Brooklyn,Williamsburg,40.70933,-73.96792,Entire home/apt,271,1,172,2020-07-14,1.44,1,365,371
201,61747,"Cozy, Brooklyn, Prospect Park Studio",299370,David,Brooklyn,Prospect-Lefferts Gardens,40.65979,-73.96180,Entire home/apt,91,14,97,2018-01-31,0.83,1,44,91
209,62903,Beautiful modern studio apartment in heart of NYC,306605,Daniel,Manhattan,Chelsea,40.74238,-73.99567,Entire home/apt,205,15,68,2019-12-14,0.67,2,89,205
220,64015,Prime East Village 1 Bedroom,146944,David,Manhattan,East Village,40.72807,-73.98594,Entire home/apt,200,3,0,NaN,NaN,1,0,200
260,74073,Food & Music Dream Apartment in Williamsburg,211877,Daniel,Brooklyn,Williamsburg,40.71113,-73.96054,Entire home/apt,187,30,90,2020-07-31,0.81,1,261,287

In [21]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 

in_williamsburg = df[ 'neighbourhood' ] == 'Williamsburg'
df[ 'adjusted_price' ] = np.where( in_williamsburg, df.price + 100 , df.price)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,adjusted_price
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365,175
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265,75
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365,60
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295,175
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340,65
5,5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.80178,-73.96723,Private room,75,2,118,2017-07-21,0.89,1,0,75
6,5238,Cute & Cozy Lower East Side 1 bdrm,7549,Ben,Manhattan,Chinatown,40.71344,-73.99037,Entire home/apt,140,1,161,2019-07-29,1.21,4,274,140
7,5552,Spacious river view in the West Village,8380,Maria,Manhattan,West Village,40.73552,-74.01042,Entire home/apt,160,3,66,2019-08-10,0.49,1,178,160
8,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,88,4,180,2020-03-18,1.31,3,344,88
9,6021,Wonderful Guest Bedroom in Manhattan CENTRAL PARK,11528,Claudio,Manhattan,Upper West Side,40.79826,-73.96113,Private room,85,2,123,2019-12-09,0.90,1,365,85
10,6090,West Village Nest - Superhost,11975,Alina,Manhattan,West Village,40.73530,-74.00525,Entire home/apt,65,30,29,2020-07-25,0.22,1,197,65
11,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,109,2,181,2020-03-16,1.32,1,0,209
12,6990,UES Beautiful Blue Room / 2 Bedrooms,16800,Cyn,Manhattan,East Harlem,40.78962,-73.94802,Entire home/apt,239,4,233,2019-12-09,1.77,1,365,239
13,7097,Perfect for Your Parents + Garden; Germ-Free,17571,Jane,Brooklyn,Fort Greene,40.69121,-73.97277,Entire home/apt,182,1,229,2020-07-20,1.78,2,325,182
14,7750,2 Furnished bedrooms next to Central Park,17985,Sing,Manhattan,East Harlem,40.79685,-73.94872,Private room,96,14,0,NaN,NaN,2,178,96

In [43]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  

dfp = df.room_type.value_counts() / df.room_type.value_counts().sum()
dfp[ [ 'Private room', 'Shared room' ] ]

Private room    0.454446
Shared room     0.021213
Name: room_type, dtype: float64

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [ ]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.

In [ ]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups.

In [ ]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups.

In [ ]:
# 4. Using `groupby`, find the mean price for each room type in each neighbourhood_group.

In [ ]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.

# Join and file saving.
1. Load the `prices.csv` and the `n_listings.csv`


2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']
       
       
3. Save your joined csv as `joined.csv`


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [ ]:
# 1. Load the `prices.csv` and the `n_listings.csv`

In [ ]:
# 2. Do join that keeps all the records for each table.

# Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

In [ ]:
#  1. Who was won Album of the Year in 2016?

In [ ]:
# 2. Who won Best Rap Album in 2009?

In [ ]:
# 3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?